version: '3.8'

services:
  web:
    container_name: blog-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 127.0.0.1:8000
    env_file:
      - config/.env
    volumes:
      - .:/app
    ports:
      - 8000:8000
